#security:
#  basic:
#    enabled: true
#  user:
#    name: user
#    password: password
server:
  port: 8761
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: false
    fetch-registry: false
    healthcheck:
      enabled: true
