server:
  port: 8010
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    heartcheck:
      enabled: true
  instance:
    prefer-ip-address: true
spring:
  application:
    name: simple-consumer-movie-ribbon